### ISSUE TITLE
Images don't show up on feed and user page

### ISSUE THREAD

**Issue by nbaldy** [ArgaAlan/CodeU-2019#135]

**Comment by drewbern** [comment]
Resolve by #136

**Comment by nbaldy** [comment]
I don't know that this particular issue was resolved, on my Feed it still isn't showing images 
![image](https://user-images.githubusercontent.com/29146809/56461995-b59ac800-6389-11e9-8886-fff7b108dfe1.png)

**Comment by drewbern** [comment]
Oops! My bad

**Comment by drewbern** [comment]
@nbaldy Is this locally or in the cloud appengine?

**Comment by drewbern** [comment]
Addressed in #137
