### ISSUE TITLE
SSR appropriate web pages

### ISSUE THREAD

**Issue by nbaldy** [ArgaAlan/CodeU-2019#38]
- Need to read up on SSR and discuss with team what web pages should be altered to use SSR
-Then, need to implement these changes

**Comment by drewbern** [comment]
Currently, the entire index and user page is SSRed. Paged not currently using SSR include the feed and the map pages. I think the feed would be an easy page to SSR

**Comment by nbaldy** [comment]
I feel like I need to better understand when we should SSR; I believe that the tutorial said that client-side rendering is often used for "infinite scrolling", where it loads a chunk, then if you scroll to the top, it loads more, etc. I think this might make more sense than trying to show every single message or not allowing the user to scroll past a single point... but I don't know, because I don't really understand completely. 
What do you think? @acolwell @drewbern
