### ISSUE TITLE
Error.jsp not working on appengine

### ISSUE THREAD

**Issue by nbaldy** [ArgaAlan/CodeU-2019#93]
Appengine
![image](https://user-images.githubusercontent.com/29146809/55696767-71242b00-598c-11e9-8240-aed7b52b5338.png)

Local devserver
![image](https://user-images.githubusercontent.com/29146809/55696827-b21c3f80-598c-11e9-8bfb-b54ac7f2f317.png)

**Comment by drewbern** [comment]
From the research that I've done online, it seems like this something to do with the app engine server. I'm did a bunch of googling related to "google app engine 404 page" but to no avail.

**Comment by nbaldy** [comment]
Huh, that's interesting. I'll maybe try taking out the error response later and see if that fixes it?

**Comment by nbaldy** [comment]
#101
