### ISSUE TITLE
Country page and category page have "User Page" title bar

### ISSUE THREAD

**Issue by nbaldy** [ArgaAlan/CodeU-2019#94]
![image](https://user-images.githubusercontent.com/29146809/55760806-34f3d780-5a2b-11e9-95c4-b3597bff798a.png)
![image](https://user-images.githubusercontent.com/29146809/55760815-3e7d3f80-5a2b-11e9-9d61-bca808080399.png)

**Comment by drewbern** [comment]
Should the countries have different size headers? Or what do you suggest?

**Comment by nbaldy** [comment]
@drewbern sorry for being vague, I don't know what it's called, but it's the part on the tab that I'm talking about 
![image](https://user-images.githubusercontent.com/29146809/55770283-b9595100-5a51-11e9-9bca-d9a40083ce1a.png)

**Comment by nbaldy** [comment]
Fixed in #103
