### ISSUE TITLE
Error page link to user page broken

### ISSUE THREAD

**Issue by nbaldy** [ArgaAlan/CodeU-2019#96]
![image](https://user-images.githubusercontent.com/29146809/55768291-4ef0e280-5a4a-11e9-8563-9f7c49ee6d80.png)

Not sure when it happened, but that should be fixed soon

**Comment by nbaldy** [comment]
My guess is my PR #83

**Comment by drewbern** [comment]
@nbaldy Possibly unrelated, but can you briefly tell me how a page like /foo is routed to the error.jsp? I've been trying to figure it out, but I'm not sure. I know that error.jsp has a scriptlet getAttribute function, but where is the attribute set?

**Comment by nbaldy** [comment]
So it's actually in the HomeServlet, 
![image](https://user-images.githubusercontent.com/29146809/55770108-291b0c00-5a51-11e9-8c17-cd1d64ed4712.png)
Aaron helped me to implement it; essentially, it's kind of like super-wildcarding, in that due to our HomeServlet being "/", it catches everything that doesn't have its own servlet or page; therefore, this logic just basically says that anything that's not a call for just "/" doesn't have a page, so we forward the request to the error page.

**Comment by nbaldy** [comment]
(I think)

**Comment by nbaldy** [comment]
Fiixed in #101
